// @ts-check
// `@type` JSDoc annotations allow editor autocompletion and type checking
// (when paired with `@ts-check`).
// There are various equivalent ways to declare your Docusaurus config.
// See: https://docusaurus.io/docs/api/docusaurus-config

import { themes as prismThemes } from "prism-react-renderer";

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: "SDK Mobile Documentation",
  tagline: "Facephi",
  favicon: "img/icon.png",

  staticDirectories: ["static"],
  // Set the production url of your site here
  url: "https://facephi.github.io",
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: "/",

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: "facephi", // Usually your GitHub org/user name.
  projectName: "sdk-mobile-documentation", // Usually your repo name.

  onBrokenLinks: "throw",
  onBrokenMarkdownLinks: "warn",

  // Even if you don't use internationalization, you can use this field to set
  // useful metadata like html lang. For example, if your site is Chinese, you
  // may want to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: "en",
    locales: ["en", "es"],
  },
  presets: [
    [
      "@docusaurus/preset-classic",
      {
        docs: {
          id: "android", // omitted => default instance
          path: "docs/android",
          routeBasePath: "docs/android",
          sidebarPath: "./sidebarsAndroid.js",
          // ... other options
        },
        theme: {
          customCss: "./src/css/custom.css",
        },
      },
    ],
    /*
    
    [
      "@docusaurus/preset-classic",
      {
        docs: {
          id: "ios", // omitted => default instance
          path: "ios",
          routeBasePath: "ios",
          sidebarPath: "./sidebars.js",
          // ... other options
        },
        theme: {
          customCss: "./src/css/custom.css",
        },
      },
    ],
    */
  ],
  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      // Replace with your project's social card
      image: "img/docusaurus-social-card.jpg",
      sidebar: {
        path: "android", // Path to the docs folder
        sidebar: {
          // Specify that the sidebar should be autogenerated
          auto: true,
        },
      },
      navbar: {
        title: "SDK Mobile Documentation",
        logo: {
          alt: "SDK Mobile Logo",
          src: "img/icon.png",
        },
        items: [
          {
            type: "docsVersion",
            position: "left",
            label: "Android",
            docsPluginId: "android",
          },
          {
            type: "docsVersion",
            position: "left",
            label: "iOS",
            docsPluginId: "ios",
          },
          {
            type: "docsVersion",
            position: "left",
            label: "Flutter",
            docsPluginId: "flutter",
          },
          {
            type: "docsVersion",
            position: "left",
            label: "Cordova",
            docsPluginId: "cordova",
          },
          {
            type: "docsVersion",
            position: "left",
            label: "React Native",
            docsPluginId: "react",
          },
          {
            type: "docsVersionDropdown",
            docsPluginId: "android",
            position: "right",
            customCss: "menu-android",
          },
          {
            type: "docsVersionDropdown",
            docsPluginId: "ios",
            position: "right",
            customCss: "menu-ios",
          },
          {
            type: "docsVersionDropdown",
            docsPluginId: "flutter",
            position: "right",
            customCss: "menu-flutter",
          },
          {
            type: "docsVersionDropdown",
            docsPluginId: "cordova",
            position: "right",
            customCss: "menu-cordova",
          },
          {
            type: "docsVersionDropdown",
            docsPluginId: "react",
            position: "right",
            customCss: "menu-react",
          },
          {
            type: "localeDropdown",
            position: "right",
          },
          {
            href: "https://github.com/facephi/sdk-mobile-samples",
            label: "GitHub",
            position: "right",
          },
        ],
      },
      footer: {
        style: "dark",
        copyright: `Copyright © ${new Date().getFullYear()} SDK Mobile, Facephi.`,
      },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
      },
    }),
  plugins: [
    /*
    [
      "@docusaurus/plugin-content-docs",
      {
        // id: 'product', // omitted => default instance
        path: "android",
        routeBasePath: "android",
        sidebarPath: "./sidebarsAndroid.js",
        // ... other options
      },
    ],
    */
    [
      "@docusaurus/plugin-content-docs",
      {
        id: "ios",
        path: "docs/ios",
        routeBasePath: "docs/ios",
        sidebarPath: "./sidebarsIOS.js",
        // ... other options
      },
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        id: "flutter",
        path: "docs/flutter",
        routeBasePath: "docs/flutter",
        sidebarPath: "./sidebarsFlutter.js",
        // ... other options
      },
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        id: "cordova",
        path: "docs/cordova",
        routeBasePath: "docs/cordova",
        sidebarPath: "./sidebarsCordova.js",
        // ... other options
      },
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        id: "react",
        path: "docs/react",
        routeBasePath: "docs/react",
        sidebarPath: "./sidebarsReact.js",
        // ... other options
      },
    ],
  ],
};

export default config;
