/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Android",
      items: [
        "en-android/1.5.X_EN_Android_Mobile_SDK",
        "en-android/1.5.X_EN_NFC_Component",
        "en-android/1.5.X_EN_Phingers_Component",
        "en-android/1.5.X_EN_Selphi_Component",
        "en-android/1.5.X_EN_SelphID_Component",
        "en-android/1.5.X_EN_Tracking_Component",
        "en-android/1.5.X_EN_Video_Call_Component",
        "en-android/1.5.X_EN_Video_Id_Component",
        "en-android/1.5.X_EN_Video_Recording_Component",
        "en-android/1.5.X_EN_Voice_Component",
      ],
    },
  ],
};

export default sidebars;
